/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ConnectionDB;
import dao.DateTime;
import Api.test.ExecPy;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class UI extends javax.swing.JFrame {
    public char ia;
    public int op;
    private String ut; 
    private java.io.File currentFile;
    
    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        
        getContentPane().setBackground(new Color(0,49,83));
        ImageIcon icone = new ImageIcon("bender.png");
        jLabel3.setIcon(icone);
                
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        Documentacao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Historico = new javax.swing.JButton();
        document = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        analise = new javax.swing.JMenuItem();
        explicacao = new javax.swing.JMenuItem();
        sugestao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bot Echo IDE");
        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(java.awt.Color.blue);

        Documentacao.setColumns(20);
        Documentacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Documentacao.setRows(5);
        jScrollPane1.setViewportView(Documentacao);
        Documentacao.getAccessibleContext().setAccessibleName("areaUsuario");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton3.setText("Run");
        jButton3.setMaximumSize(new java.awt.Dimension(94, 24));
        jButton3.setMinimumSize(new java.awt.Dimension(94, 24));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Historico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Historico.setText("Histórico");
        Historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Historico(evt);
            }
        });

        document.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        document.setText("Documentação");
        document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Documentacao(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BotEcho");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Input");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Output");

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Abrir arquivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salvar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salvar como...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Inteligência Artificial (IA)");

        analise.setText("Realizar análise");
        analise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analiseActionPerformed(evt);
            }
        });
        jMenu5.add(analise);

        explicacao.setText("Gerar explicação");
        explicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explicacaoActionPerformed(evt);
            }
        });
        jMenu5.add(explicacao);

        sugestao.setText("Sugestões de melhoria");
        sugestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugestaoActionPerformed(evt);
            }
        });
        jMenu5.add(sugestao);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Historico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(document, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(jLabel4))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Historico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(document)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        getAccessibleContext().setAccessibleName("BotEcho IDE");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ExecPy ep = new ExecPy();
        ep.exec(Documentacao.getText());
        jTextArea2.setText(ep.getRes());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Historico(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Historico
        Connection conn = ConnectionDB.connectDB();

        try {
            String[] opcoes = {"Análise", "Explicação", "Sugestão", "Documentação"};
            String[] colunas = new String[]{
                "Nome", "Data", "Resposta", "Tipo"
            };

            int op = JOptionPane.showOptionDialog(null, "Escolha o tipo dos prompts:", "Histórico de Visualizações", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcoes, opcoes[0]);

            if (op == 0) {
                ia = 'A';
            } else if (op == 1) {
                ia = 'E';
            } else if (op == 2) {
                ia = 'S';
            } else if (op == 3){
                ia = 'D';
            } else if (op == JOptionPane.CLOSED_OPTION) {
                return;
            }

            DefaultTableModel tabelaHist = new DefaultTableModel(colunas, 0);
            ArrayList<Object[]> historico = ConnectionDB.selectDB(conn, ia);

            for (Object[] h : historico) {
                tabelaHist.addRow(h);
            }

            JTable tabelaHistorico = new JTable(tabelaHist);
            tabelaHistorico.setRowHeight(20);
            TableColumnModel columnModel = tabelaHistorico.getColumnModel();
            columnModel.getColumn(0).setWidth(100);
            columnModel.getColumn(1).setPreferredWidth(60);
            columnModel.getColumn(2).setPreferredWidth(250);
            columnModel.getColumn(3).setPreferredWidth(10);
            JFrame frameHistorico = new JFrame("Histórico de Prompts");
            frameHistorico.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            JScrollPane scroll = new JScrollPane(tabelaHistorico);
            frameHistorico.getContentPane().add(scroll);
            frameHistorico.pack();
            frameHistorico.setLocationRelativeTo(null);
            frameHistorico.setVisible(true);

            tabelaHistorico.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    int row = tabelaHistorico.rowAtPoint(evt.getPoint());
                    JScrollPane scroll = new JScrollPane(tabelaHistorico);

                    if (row >= 0) {
                        Object nome = tabelaHistorico.getValueAt(row, 0);
                        Object data = tabelaHistorico.getValueAt(row, 1);
                        Object resposta = tabelaHistorico.getValueAt(row, 2);

                        Documentacao.setText("Nome: " + nome + "\nData: " + data + "\nResposta: \n" + resposta);
                        frameHistorico.dispose();
                    }
                }
            });

        } catch (SQLException er) {
            er.printStackTrace();
        } catch (Exception er) {
            throw new RuntimeException(er);
        }
    }//GEN-LAST:event_Historico


    private void Documentacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Documentacao
        Connection conn = ConnectionDB.connectDB();
        Prompt prompt = new Prompt();

        try {
            prompt.Document(Documentacao.getText());
            jTextArea2.setText(prompt.respostaBot());
            ConnectionDB.insertDB(conn, prompt.respostaBot(), prompt.Utilidade(), 'D', prompt.Nome(), DateTime.getDataTime());
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error generating documentation");
            System.out.println("Error: " + e.getMessage());

        }

        jTextArea2.setText(prompt.respostaBot());

    }//GEN-LAST:event_Documentacao

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    int result = fileChooser.showOpenDialog(this);
    
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        this.currentFile = fileChooser.getSelectedFile();
        try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader(this.currentFile))) {
            StringBuilder conteudo = new StringBuilder();
            String linha;
            setTitle("Bot Echo IDE - " + this.currentFile.getName());
            while ((linha = reader.readLine()) != null) {
                conteudo.append(linha).append("\n");
            }
            Documentacao.setText(conteudo.toString());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar arquivo: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (this.currentFile == null) {
            jMenuItem3ActionPerformed(evt);
        } else {
            try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter(this.currentFile))) {
                writer.write(Documentacao.getText());
                javax.swing.JOptionPane.showMessageDialog(this, "Arquivo salvo com sucesso!");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar arquivo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(java.io.File f) {
                return f.isDirectory() || f.getName().endsWith(".py");
            }
            @Override
            public String getDescription() {
                return "Python File (*.py)";
            }
        });
        int result = fileChooser.showSaveDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            this.currentFile = fileChooser.getSelectedFile();
            if (!this.currentFile.getName().endsWith(".py")) {
              this.currentFile = new java.io.File(this.currentFile.getParent(),this.currentFile.getName() + ".py");
            }

            if (this.currentFile.exists()) {
                int overwrite = javax.swing.JOptionPane.showConfirmDialog(this,
                        "O arquivo já existe. Deseja substituí-lo?",
                        "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
                if (overwrite != javax.swing.JOptionPane.YES_OPTION) {
                    return;
                }
            }

            try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter(this.currentFile))) {
                writer.write(Documentacao.getText());
                setTitle("Bot Echo IDE - " + this.currentFile.getName());
                javax.swing.JOptionPane.showMessageDialog(this, "Arquivo salvo com sucesso!");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar arquivo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void analiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analiseActionPerformed
        Prompt prompt = new Prompt();
        Connection conn = ConnectionDB.connectDB();

        try {
            prompt.Analise(Documentacao.getText());
            jTextArea2.setText(prompt.respostaBot());

            ConnectionDB.insertDB(conn, prompt.respostaBot(), prompt.Utilidade(), 'A', prompt.Nome(), DateTime.getDataTime());
        } catch (Exception e) {
            e.printStackTrace(); // Print error details
            System.out.print("An error occurred: " + e.getMessage());
        }
    }//GEN-LAST:event_analiseActionPerformed

    private void explicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explicacaoActionPerformed
        Prompt prompt = new Prompt();
        Connection conn = ConnectionDB.connectDB();

        try {
            prompt.Explicacao(Documentacao.getText());
            jTextArea2.setText(prompt.respostaBot());

            ConnectionDB.insertDB(conn, prompt.respostaBot(), prompt.Utilidade(), 'E', prompt.Nome(), DateTime.getDataTime());
        } catch (Exception e) {
            e.printStackTrace(); // Print error details
            System.out.print("An error occurred: " + e.getMessage());
        }
    }//GEN-LAST:event_explicacaoActionPerformed

    private void sugestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugestaoActionPerformed
        Prompt prompt = new Prompt();
        Connection conn = ConnectionDB.connectDB();

        try {
            prompt.Sugestao(Documentacao.getText());
            jTextArea2.setText(prompt.respostaBot());

            ConnectionDB.insertDB(conn, prompt.respostaBot(), prompt.Utilidade(), 'S', prompt.Nome(), DateTime.getDataTime());
        } catch (Exception e) {
            e.printStackTrace(); // Print error details
            System.out.print("An error occurred: " + e.getMessage());
        }
        jTextArea2.setText(prompt.respostaBot());
    }//GEN-LAST:event_sugestaoActionPerformed
          
            
    /**
     * @param args the command line  
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
    });
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Documentacao;
    private javax.swing.JButton Historico;
    private javax.swing.JMenuItem analise;
    private javax.swing.JToggleButton document;
    private javax.swing.JMenuItem explicacao;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenuItem sugestao;
    // End of variables declaration//GEN-END:variables
}
